services:
  fpm:
    build:
      context: .docker/local/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - project-dev

  nginx:
    build:
      context: .docker/local/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - project-dev
    depends_on:
      fpm:
        condition: service_started

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    networks:
      - project-dev
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  ###> mailer ###
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - project-dev
  ###< mailer ###

networks:
  project-dev:
    driver: bridge

volumes:
  database_data:
